from datetime import timedelta

from ..models import SubscriptionType, PaymentPurposePrice, ColorProperties, ClarityProperties, CutProperties, \
    PolishProperties, SymmetryProperties
from ..models.enums import PaymentPurpose, Color, Clarity, Quality

values = [
    SubscriptionType(
        name='Monthly',
        duration=timedelta(days=30),
        max_diamonds_per_load=3000,
        total_new_diamonds_per_period=5000
    ),

    PaymentPurposePrice(
        purpose=PaymentPurpose.SUBSCRIPTION_RENEWAL,
        usd_price=11
    ),
    PaymentPurposePrice(
        purpose=PaymentPurpose.CONTACTS_PURCHASE,
        usd_price=2
    ),

    ColorProperties(
        color=Color.D,
        index=0,
        group=0
    ),
    ColorProperties(
        color=Color.E,
        index=1,
        group=0
    ),
    ColorProperties(
        color=Color.F,
        index=2,
        group=0
    ),
    ColorProperties(
        color=Color.G,
        index=3,
        group=1
    ),
    ColorProperties(
        color=Color.H,
        index=4,
        group=1
    ),
    ColorProperties(
        color=Color.I,
        index=5,
        group=1
    ),
    ColorProperties(
        color=Color.J,
        index=6,
        group=1
    ),
    ColorProperties(
        color=Color.K,
        index=7,
        group=2
    ),
    ColorProperties(
        color=Color.L,
        index=8,
        group=2
    ),
    ColorProperties(
        color=Color.M,
        index=9,
        group=2
    ),
    ColorProperties(
        color=Color.N,
        index=10,
        group=2
    ),

    ClarityProperties(
        clarity=Clarity.FL,
        index=0,
        group=0
    ),
    ClarityProperties(
        clarity=Clarity.IF,
        index=1,
        group=0
    ),
    ClarityProperties(
        clarity=Clarity.VVS1,
        index=2,
        group=0
    ),
    ClarityProperties(
        clarity=Clarity.VVS2,
        index=3,
        group=0
    ),
    ClarityProperties(
        clarity=Clarity.VS1,
        index=4,
        group=1
    ),
    ClarityProperties(
        clarity=Clarity.VS2,
        index=5,
        group=1
    ),
    ClarityProperties(
        clarity=Clarity.SI1,
        index=6,
        group=2
    ),
    ClarityProperties(
        clarity=Clarity.SI2,
        index=7,
        group=2
    ),
    ClarityProperties(
        clarity=Clarity.SI3,
        index=8,
        group=2
    ),
    ClarityProperties(
        clarity=Clarity.I1,
        index=9,
        group=3
    ),
    ClarityProperties(
        clarity=Clarity.I2,
        index=10,
        group=3
    ),
    ClarityProperties(
        clarity=Clarity.I3,
        index=11,
        group=3
    ),

    CutProperties(
        cut=Quality.EXCELLENT,
        index=0
    ),
    CutProperties(
        cut=Quality.VERY_GOOD,
        index=1
    ),
    CutProperties(
        cut=Quality.GOOD,
        index=2
    ),
    CutProperties(
        cut=Quality.POOR,
        index=3
    ),

    PolishProperties(
        polish=Quality.EXCELLENT,
        index=0
    ),
    PolishProperties(
        polish=Quality.VERY_GOOD,
        index=1
    ),
    PolishProperties(
        polish=Quality.GOOD,
        index=2
    ),
    PolishProperties(
        polish=Quality.POOR,
        index=3
    ),

    SymmetryProperties(
        symmetry=Quality.EXCELLENT,
        index=0
    ),
    SymmetryProperties(
        symmetry=Quality.VERY_GOOD,
        index=1
    ),
    SymmetryProperties(
        symmetry=Quality.GOOD,
        index=2
    ),
    SymmetryProperties(
        symmetry=Quality.POOR,
        index=3
    ),
]
